version: '3.3'
services:
  mongos:
    image: 'mongo'
    restart: always
    ports:
      - '27017:27017'
  nextjs:
    restart: always
    image: 'evilbook/docker_multi_eztit'
    ports:
        - "3000:3000"
