import React from "react";
import { useRouter } from "next/router";
export default function PaymentSuccessful({ type, value, tokenCost }) {
  const router = useRouter();

  return (
    <div className="payment-success flex-center-center flex-col">
      <style jsx>{`
        .payment-success {
          margin-top: 2em;
          text-align: center;
        }
        .payment-success_svg {
          width: 250px;
          height: 250px;
          stroke: green;
          stroke-width: 1;
        }
        .payment-success_title {
          font-size: var(--fs-500);
          color: var(--clr-neutral-800);
        }
        .payment-success_title {
          font-size: var(--fs-500);
          color: var(--clr-neutral-800);
        }
        .payment-success_subtitle {
          font-size: var(--fs-300);
          color: var(--clr-neutral-700);
        }
        .return_custom_wrapper {
          margin-left: auto;
        }
        .payment-success_item {
          background: #288ee233;
          padding: 0.5em 0.8em;
          border-radius: 100px;
          color: var(--clr-neutral-800);
        }
        .payment-success_item strong {
          color: var(--clr-primary);
          text-transform: uppercase;
        }
        /***************************************************
 * Generated by SVG Artista on 3/23/2022, 1:21:16 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

        @-webkit-keyframes animate-svg-stroke-1 {
          0% {
            stroke-dashoffset: 66.25031280517578px;
            stroke-dasharray: 66.25031280517578px;
          }

          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 66.25031280517578px;
          }
        }

        @keyframes animate-svg-stroke-1 {
          0% {
            stroke-dashoffset: 66.25031280517578px;
            stroke-dasharray: 66.25031280517578px;
          }

          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 66.25031280517578px;
          }
        }

        .payment_success-svg-1 {
          -webkit-animation: animate-svg-stroke-1 0.5s
            cubic-bezier(0.755, 0.05, 0.855, 0.06) 0s both;
          animation: animate-svg-stroke-1 0.5s
            cubic-bezier(0.755, 0.05, 0.855, 0.06) 0s both;
        }
      `}</style>

      <a
        className="return_custom_wrapper"
        href="/services-portal?account=payment"
      >
        <div
          className="return_custom"
          /*onClick={() => router.replace("/services-portal?account=payment")}*/
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            className="return_icon"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            strokeWidth={2}
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M11 15l-3-3m0 0l3-3m-3 3h8M3 12a9 9 0 1118 0 9 9 0 01-18 0z"
            />
          </svg>
          <span className="return_text">Return to Custom Payment</span>
        </div>
      </a>

      <svg
        xmlns="http://www.w3.org/2000/svg"
        className="payment-success_svg"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
        strokeWidth="{2}"
        width="24"
        height="24"
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          d="M9 12l2 2 4-4M7.835 4.697a3.42 3.42 0 001.946-.806 3.42 3.42 0 014.438 0 3.42 3.42 0 001.946.806 3.42 3.42 0 013.138 3.138 3.42 3.42 0 00.806 1.946 3.42 3.42 0 010 4.438 3.42 3.42 0 00-.806 1.946 3.42 3.42 0 01-3.138 3.138 3.42 3.42 0 00-1.946.806 3.42 3.42 0 01-4.438 0 3.42 3.42 0 00-1.946-.806 3.42 3.42 0 01-3.138-3.138 3.42 3.42 0 00-.806-1.946 3.42 3.42 0 010-4.438 3.42 3.42 0 00.806-1.946 3.42 3.42 0 013.138-3.138z"
          className="payment_success-svg-1"
        ></path>
      </svg>
      <h2 className="payment-success_title">Payment Successful:</h2>
      <p className="payment-success_item">
        <strong>{type}</strong> : {type === "tokens" ? tokenCost : value}
      </p>
      <p className="payment-success_subtitle">Thanks you for your payment.</p>
      <p className="payment-success_subtitle">
        We will be sending you an email shortly with all the whatever deatils.
      </p>
    </div>
  );
}
