# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - rjss

on:
  push:
    branches:
      - azure
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

          #  - name: Create env file
          #   run: |
          #    touch .env
          #   echo API_ENDPOINT=
          #  echo API_KEY=${{ secrets.API_KEY }} >> .env
          # EMAIL_USER=AKIAUE4LVMWRBOJQKQ7T
          #EMAIL_PASSWORD=BNefYeh8TtzjURa9e7XX85LpThCjco902Z5uijJA5+N+
          #EMAIL_HOST=email-smtp.eu-central-1.amazonaws.com
          #EMAIL_PORT=587
          #EMAIL_FROM=real.martin.zannato@gmail.com
          #cat .env

      - name: npm install, build, and test
        run: |
          npm install --force
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip * .next
          rm -r .next node_modules public

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: unzip artifact for deployment
        run: |
          unzip -o release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'rjss'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BA49E7E8C24D4011B444E50E167F8B3A }}
          package: .
